language: generic 
# Need super user permission when dealing with docker
sudo: required

# Tell travis that we need docker cli pre-installed
services:
  - docker

# Series of commands to be executed before our commands are ran
before_install:
  # Tag the image because we will not have access to the ID of the image generated afterward
  - docker build -t cainuse/docker-react -f Dockerfile.dev .

# Tell Travis how to run our tests
script:
  - docker run -e CI=true cainuse/docker-react npm run test

# Tell Travis where to deploy to after the tests pass
deploy:
  # By default travis has support for many cloud providers
  provider: elasticbeanstalk
  # Specify the region of the environment (can be found within the environment url)
  region: "us-east-2"
  app: "cicdDemo"
  env: "Cicddemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-896110773121"
  # We need to specify the "folder" of the bucket as the bucket is shared among many apps
  bucket_path: "cicdDemo"
  # Tel Travis when to deploy (In this case when main branch is updated)
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"